# Generated by Django 6.0.4 on 2026-05-09 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floor',
            name='floor_type',
            field=models.CharField(choices=[('RETAIL', 'Retail'), ('OFFICE', 'Office')], default='RETAIL', max_length=10),
        ),
    ]
