# Generated by Django 6.0.4 on 2026-05-10 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_alter_floor_floor_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='svg_filename',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
